name: dear_deer_demo
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  logger: ^2.5.0
  intl: ^0.20.2
  flutter_screenutil: ^5.9.3
  get: ^4.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^3.0.0


flutter:
  uses-material-design: true
  assets:
  - assets/images/