// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCUMzgzOkfPIOqPZ2gdiRBe9HCuHYg8rUQ',
    appId: '1:179953528227:web:7140c5272715d84805be16',
    messagingSenderId: '179953528227',
    projectId: 'dear-deer-ca3b2',
    authDomain: 'dear-deer-ca3b2.firebaseapp.com',
    storageBucket: 'dear-deer-ca3b2.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBR8ESLkChcECyN4ZSwb4VBZyieWFl5u8g',
    appId: '1:179953528227:android:ce133faa225ee89805be16',
    messagingSenderId: '179953528227',
    projectId: 'dear-deer-ca3b2',
    storageBucket: 'dear-deer-ca3b2.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAPul2reJccKfy7kSuHB0ApmQommzhbpGg',
    appId: '1:179953528227:ios:8eb250eb3de70ee805be16',
    messagingSenderId: '179953528227',
    projectId: 'dear-deer-ca3b2',
    storageBucket: 'dear-deer-ca3b2.firebasestorage.app',
    iosBundleId: 'com.example.dearDeerDemo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAPul2reJccKfy7kSuHB0ApmQommzhbpGg',
    appId: '1:179953528227:ios:8eb250eb3de70ee805be16',
    messagingSenderId: '179953528227',
    projectId: 'dear-deer-ca3b2',
    storageBucket: 'dear-deer-ca3b2.firebasestorage.app',
    iosBundleId: 'com.example.dearDeerDemo',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCUMzgzOkfPIOqPZ2gdiRBe9HCuHYg8rUQ',
    appId: '1:179953528227:web:2e0ee5ddb563cae005be16',
    messagingSenderId: '179953528227',
    projectId: 'dear-deer-ca3b2',
    authDomain: 'dear-deer-ca3b2.firebaseapp.com',
    storageBucket: 'dear-deer-ca3b2.firebasestorage.app',
  );
}
